"""create sensor_samples

Revision ID: 88350bd75993
Revises:
Create Date: 2026-02-01 21:28:41.942191

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import Column, Float, String, TIMESTAMP, null


# revision identifiers, used by Alembic.
revision: str = "88350bd75993"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "sensor_samples",
        Column("ts", TIMESTAMP(timezone=True), primary_key=True, nullable=False),
        Column("session_id", String, primary_key=True),
        Column("value", Float, nullable=False),
    )
    op.execute(
        "SELECT create_hypertable('sensor_samples', 'ts', if_not_exists => TRUE);"
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
